
import React, { useState } from 'react';
import { Trash2, AlertCircle, CheckCircle2, Loader2, Info } from 'lucide-react';
import { JunkCategory } from '../types';

const Cleaner: React.FC = () => {
  const [isScanning, setIsScanning] = useState(false);
  const [isCleaned, setIsCleaned] = useState(false);
  const [categories, setCategories] = useState<JunkCategory[]>([
    { id: '1', name: 'System Cache', description: 'Temporary files created by macOS system and apps.', size: 4.2, checked: true },
    { id: '2', name: 'Application Logs', description: 'Log files generated by applications.', size: 1.8, checked: true },
    { id: '3', name: 'Trash Bin', description: 'Files you have deleted but not emptied.', size: 12.5, checked: false },
    { id: '4', name: 'Browser Cache', description: 'Images and scripts cached by Safari and Chrome.', size: 2.1, checked: true },
    { id: '5', name: 'Unused Languages', description: 'Localization files for languages you don\'t use.', size: 0.9, checked: true },
  ]);

  const totalSelected = categories
    .filter(c => c.checked)
    .reduce((acc, curr) => acc + curr.size, 0);

  const startScan = () => {
    setIsScanning(true);
    setTimeout(() => {
      setIsScanning(false);
    }, 2500);
  };

  const startClean = () => {
    setIsScanning(true);
    setTimeout(() => {
      setIsScanning(false);
      setIsCleaned(true);
    }, 3000);
  };

  const toggleCategory = (id: string) => {
    setCategories(cats => cats.map(c => c.id === id ? { ...c, checked: !c.checked } : c));
  };

  if (isCleaned) {
    return (
      <div className="flex flex-col items-center justify-center py-20 animate-in fade-in zoom-in duration-500">
        <div className="w-24 h-24 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mb-6">
          <CheckCircle2 size={48} />
        </div>
        <h3 className="text-2xl font-bold mb-2">System Cleaned!</h3>
        <p className="text-gray-500 mb-8">You just recovered {totalSelected.toFixed(1)} GB of space.</p>
        <button 
          onClick={() => setIsCleaned(false)}
          className="px-8 py-3 bg-blue-500 text-white rounded-2xl font-semibold hover:bg-blue-600 transition-colors shadow-lg shadow-blue-200"
        >
          Done
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="glass rounded-3xl p-8 flex items-center justify-between">
        <div className="flex items-center space-x-6">
          <div className="w-20 h-20 bg-blue-50 rounded-3xl flex items-center justify-center text-blue-500">
            {isScanning ? <Loader2 className="animate-spin" size={32} /> : <Trash2 size={32} />}
          </div>
          <div>
            <h3 className="text-xl font-bold">Deep Cleaning</h3>
            <p className="text-gray-500 text-sm">Select categories to safely remove junk from your Mac.</p>
          </div>
        </div>
        <div className="text-right">
          <div className="text-3xl font-bold text-blue-500">{totalSelected.toFixed(1)} GB</div>
          <div className="text-xs text-gray-400 font-medium uppercase tracking-wider">SELECTED SPACE</div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {categories.map((cat) => (
          <div 
            key={cat.id}
            onClick={() => toggleCategory(cat.id)}
            className={`glass rounded-2xl p-5 cursor-pointer border transition-all duration-200 flex items-center space-x-4 ${
              cat.checked ? 'border-blue-500 ring-1 ring-blue-500 bg-blue-50/30' : 'border-transparent hover:bg-white/80'
            }`}
          >
            <div className={`w-6 h-6 rounded-md border flex items-center justify-center transition-colors ${
              cat.checked ? 'bg-blue-500 border-blue-500 text-white' : 'bg-white border-gray-300'
            }`}>
              {cat.checked && <CheckCircle2 size={14} />}
            </div>
            <div className="flex-1">
              <div className="flex items-center justify-between">
                <span className="font-bold">{cat.name}</span>
                <span className="text-gray-500 font-medium">{cat.size} GB</span>
              </div>
              <p className="text-xs text-gray-400 mt-1 line-clamp-1">{cat.description}</p>
            </div>
            <Info className="text-gray-300" size={16} />
          </div>
        ))}
      </div>

      <div className="flex items-center justify-center mt-8">
        {!isScanning ? (
          <button 
            onClick={startClean}
            disabled={totalSelected === 0}
            className="px-12 py-4 bg-blue-500 text-white rounded-2xl font-bold text-lg hover:bg-blue-600 transition-all shadow-xl shadow-blue-200 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Clean Now
          </button>
        ) : (
          <div className="flex flex-col items-center">
            <Loader2 className="animate-spin text-blue-500 mb-4" size={40} />
            <p className="text-blue-500 font-medium">Cleaning System Files...</p>
          </div>
        )}
      </div>

      <div className="flex items-start space-x-3 p-4 bg-amber-50 rounded-2xl border border-amber-100">
        <AlertCircle className="text-amber-600 shrink-0" size={20} />
        <p className="text-xs text-amber-800 leading-relaxed">
          Cleaning system cache is safe. Some apps might take slightly longer to open the first time as they rebuild their cache files.
        </p>
      </div>
    </div>
  );
};

export default Cleaner;
